// Generates src/styles/tokens.css, src/styles/tokens-deprecated.css and the DESIGN.md front matter from
// tokens/figma-variables.json (the mirror of the Figma variables).
// Architecture (D-030): Primitives → Color / Dimension (semantic) → Layout / Typography (responsive roles) → Component
// (one-offs). Every non-primitive token aliases a primitive, so each CSS variable is one var() hop from a raw value.
// Moded collections (Desktop / Mobile) emit Desktop on :root, Mobile under the page breakpoint and under
// [data-nds-mode='mobile'] (like a frame's mode in Figma), plus constants --<token>--desktop / --<token>--mobile so a
// component that switches on its own width (container query) can pick a mode explicitly.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const src = JSON.parse(readFileSync(new URL('../tokens/figma-variables.json', import.meta.url)));
const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url)));
const cssName = (name) => `--nds-${name.replaceAll('/', '-')}`;
const px = (n) => `${n}px`;
const collections = Object.entries(src).filter(([name]) => !name.startsWith('$'));
const MODE_MEDIA = { Mobile: '(max-width: 767px)' };

const cssValue = (token) => (token.alias ? `var(${cssName(token.alias)})` : token.type === 'COLOR' ? token.value : px(token.value));

// ---- tokens.css ----
const css = ['/* Generated by scripts/build-tokens.mjs — do not edit by hand. */', ':root {'];
const modeBlocks = {}; // modeName -> lines
for (const [collection, vars] of collections) {
  css.push(`  /* ${collection} */`);
  for (const [name, token] of Object.entries(vars)) {
    if (token.modes) {
      const modes = Object.keys(token.modes);
      css.push(`  ${cssName(name)}: ${cssValue({ ...token, ...token.modes[modes[0]] })};`);
      for (const m of modes) {
        css.push(`  ${cssName(name)}--${m.toLowerCase()}: ${cssValue({ ...token, ...token.modes[m] })};`);
        (modeBlocks[m] ??= []).push(`  ${cssName(name)}: var(${cssName(name)}--${m.toLowerCase()});`);
      }
    } else {
      css.push(`  ${cssName(name)}: ${cssValue(token)};`);
    }
  }
}
css.push('}');
for (const [mode, lines] of Object.entries(modeBlocks)) {
  const media = MODE_MEDIA[mode];
  if (media) css.push('', `@media ${media} {`, '  :root {', ...lines.map((l) => '  ' + l), '  }', '}');
}
for (const [mode, lines] of Object.entries(modeBlocks)) {
  css.push('', `/* Force ${mode} values for a subtree (mirrors setting a frame's mode in Figma) */`, `[data-nds-mode='${mode.toLowerCase()}'] {`, ...lines, '}');
}
css.push('');
writeFileSync(new URL('../src/styles/tokens.css', import.meta.url), css.join('\n'));

// ---- tokens-deprecated.css: retired names from the latest migration, kept as aliases for one release ----
const migUrl = new URL('../tokens/migrations/0.14.0-semantic-tokens.json', import.meta.url);
if (existsSync(migUrl)) {
  const mig = JSON.parse(readFileSync(migUrl));
  const lines = ['/* Generated by scripts/build-tokens.mjs from tokens/migrations/0.14.0-semantic-tokens.json.',
    '   Deprecated in 0.14.0, removed in 0.16.0: component-scoped names that now point at the tiered tokens.',
    '   Replace each with its target (see the migration map); nothing in this package uses them. */', ':root {'];
  for (const [old, { to, mode }] of Object.entries(mig.map)) {
    if (old === to) continue;
    lines.push(`  ${cssName(old)}: var(${cssName(to)}${mode ? `--${mode}` : ''});`);
  }
  lines.push('}', '');
  writeFileSync(new URL('../src/styles/tokens-deprecated.css', import.meta.url), lines.join('\n'));
}

// ---- DESIGN.md front matter (machine-readable tokens for Claude Code and other tools) ----
const designUrl = new URL('../DESIGN.md', import.meta.url);
if (existsSync(designUrl)) {
  const primitives = src.Primitives;
  const resolve = (token) => {
    while (token.alias) token = primitives[token.alias];
    return token.type === 'COLOR' ? token.value : px(token.value);
  };
  const q = (s) => JSON.stringify(s);
  const fm = [
    '---',
    '# Generated by `npm run tokens` from tokens/figma-variables.json. Do not edit by hand.',
    'name: Natural Design System',
    'brand: Natural',
    `version: ${pkg.version}`,
    'description: Warm, material-first UI for an online store of nature-based decorative and functional goods.',
    'figma: https://www.figma.com/design/84MjZXozBoKCvf9lwIU5pu/Natural-Design-System',
    'storybook: https://chris-terterian.github.io/natural-design-system/',
    'repository: https://github.com/chris-terterian/natural-design-system',
    'standard: WCAG 2.2 AA',
    'css_prefix: --nds-',
    'font: { family: Inter, weights: [400, 600, 700], fallback: system-ui }',
    'tiers: [Primitives, Color, Dimension, Layout, Typography, Component]',
    'modes: { Color: [Light], Layout: { Desktop: default, Mobile: "max-width 767px, data-nds-mode=mobile, or --<token>--mobile" }, Typography: same as Layout, Component: same as Layout }',
    'tokens:',
  ];
  for (const [collection, vars] of collections) {
    fm.push(`  ${q(collection)}:`);
    for (const [name, token] of Object.entries(vars)) {
      if (token.modes) {
        const parts = Object.entries(token.modes).map(([m, t]) => `${m}: { value: ${q(resolve({ ...token, ...t }))}, ref: ${q(t.alias)} }`);
        fm.push(`    ${q(name)}: { ${parts.join(', ')}, css: ${q(cssName(name))} }`);
      } else if (token.alias) {
        fm.push(`    ${q(name)}: { value: ${q(resolve(token))}, ref: ${q(token.alias)}, css: ${q(cssName(name))} }`);
      } else {
        fm.push(`    ${q(name)}: { value: ${q(resolve(token))}, css: ${q(cssName(name))} }`);
      }
    }
  }
  fm.push('---');
  const body = readFileSync(designUrl, 'utf8').replace(/^---\n[\s\S]*?\n---\n/, '');
  writeFileSync(designUrl, `${fm.join('\n')}\n${body}`);
}
// ---- Story UI docs: generated copies, so the AI reads the same brief and tokens as people do ----
const storyUiDocs = new URL('../story-ui-docs/', import.meta.url);
if (existsSync(storyUiDocs)) {
  const note = '<!-- Generated by `npm run tokens` from DESIGN.md. Do not edit here; edit DESIGN.md. -->\n';
  writeFileSync(new URL('guidelines/natural-design-system.md', storyUiDocs), note + readFileSync(designUrl, 'utf8'));
  writeFileSync(new URL('tokens/tokens.json', storyUiDocs), JSON.stringify(src, null, 2) + '\n');
}
console.log('tokens.css, tokens-deprecated.css, DESIGN.md front matter and Story UI docs written');
