// Generates src/styles/tokens.css and the DESIGN.md front matter from tokens/figma-variables.json.
// Primitives become raw values; component tokens reference primitives via var().
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const src = JSON.parse(readFileSync(new URL('../tokens/figma-variables.json', import.meta.url)));
const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url)));
const cssName = (name) => `--nds-${name.replaceAll('/', '-')}`;
const px = (n) => `${n}px`;
const collections = Object.entries(src).filter(([name]) => !name.startsWith('$'));

// ---- tokens.css ----
const css = ['/* Generated by scripts/build-tokens.mjs — do not edit by hand. */', ':root {'];
for (const [collection, vars] of collections) {
  css.push(`  /* ${collection} */`);
  for (const [name, token] of Object.entries(vars)) {
    const value = token.alias ? `var(${cssName(token.alias)})` : token.type === 'COLOR' ? token.value : px(token.value);
    css.push(`  ${cssName(name)}: ${value};`);
  }
}
css.push('}', '');
writeFileSync(new URL('../src/styles/tokens.css', import.meta.url), css.join('\n'));

// ---- DESIGN.md front matter (machine-readable tokens for Claude Code and other tools) ----
const designUrl = new URL('../DESIGN.md', import.meta.url);
if (existsSync(designUrl)) {
  const primitives = src.Primitives;
  const resolve = (token) => {
    while (token.alias) token = primitives[token.alias];
    return token.type === 'COLOR' ? token.value : px(token.value);
  };
  const q = (s) => JSON.stringify(s);
  const fm = [
    '---',
    '# Generated by `npm run tokens` from tokens/figma-variables.json. Do not edit by hand.',
    'name: Natural Design System',
    'brand: Natural',
    `version: ${pkg.version}`,
    'description: Warm, material-first UI for an online store of nature-based decorative and functional goods.',
    'figma: https://www.figma.com/design/84MjZXozBoKCvf9lwIU5pu/Natural-Design-System',
    'storybook: https://chris-terterian.github.io/natural-design-system/',
    'repository: https://github.com/chris-terterian/natural-design-system',
    'standard: WCAG 2.2 AA',
    'css_prefix: --nds-',
    'font: { family: Inter, weights: [400, 600, 700], fallback: system-ui }',
    'tokens:',
  ];
  for (const [collection, vars] of collections) {
    fm.push(`  ${q(collection)}:`);
    for (const [name, token] of Object.entries(vars)) {
      fm.push(token.alias
        ? `    ${q(name)}: { value: ${q(resolve(token))}, ref: ${q(token.alias)}, css: ${q(cssName(name))} }`
        : `    ${q(name)}: { value: ${q(resolve(token))}, css: ${q(cssName(name))} }`);
    }
  }
  fm.push('---');
  const body = readFileSync(designUrl, 'utf8').replace(/^---\n[\s\S]*?\n---\n/, '');
  writeFileSync(designUrl, `${fm.join('\n')}\n${body}`);
}
console.log('tokens.css and DESIGN.md front matter written');
