// Generates src/styles/tokens.css from tokens/figma-variables.json.
// Primitives become raw values; semantic tokens reference primitives via var().
import { readFileSync, writeFileSync } from 'node:fs';

const src = JSON.parse(readFileSync(new URL('../tokens/figma-variables.json', import.meta.url)));
const cssName = (name) => `--nds-${name.replaceAll('/', '-')}`;
const px = (n) => `${n}px`;

const lines = ['/* Generated by scripts/build-tokens.mjs — do not edit by hand. */', ':root {'];
for (const [collection, vars] of Object.entries(src)) {
  if (collection.startsWith('$')) continue;
  lines.push(`  /* ${collection} */`);
  for (const [name, token] of Object.entries(vars)) {
    const value = token.alias
      ? `var(${cssName(token.alias)})`
      : token.type === 'COLOR' ? token.value : px(token.value);
    lines.push(`  ${cssName(name)}: ${value};`);
  }
}
lines.push('}', '');
writeFileSync(new URL('../src/styles/tokens.css', import.meta.url), lines.join('\n'));
console.log('tokens.css written');
